service:
  num_replicas: 4
  ray_actor_options:
    num_cpus: 2.0
    num_gpus: 1.0
  host: &default_host
    "0.0.0.0"
  http_options:
    host: *default_host
    port: 8001
  route_prefix: "/"
  dashboard_port: 8265

api:
  feature:
    output: feats-superpoint-n4096-rmax1600
    model:
      name: superpoint
      nms_radius: 3
      max_keypoints: 4096
      keypoint_threshold: 0.005
    preprocessing:
      grayscale: True
      force_resize: True
      resize_max: 1600
      width: 640
      height: 480
      dfactor: 8
  matcher:
    output: matches-NN-mutual
    model:
      name: nearest_neighbor
      do_mutual_check: True
      match_threshold: 0.2
  dense: False
