[build]
  command = """
    git clone --recursive https://github.com/Vincentqyw/image-matching-webui.git &&
    pip install -r requirements.txt && 
    python server.py
"""
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
