[build]
  command = "pip install -r requirements.txt && python server.py"
  publish = "."

[context.production.environment]
  PYTHON_VERSION = "3.10.10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
