[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "python -m api.server"
sleepApplication = true
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10