server:
  name: "0.0.0.0"
  port: 7860

defaults:
  setting_threshold: 0.1
  max_keypoints: 2000
  keypoint_threshold: 0.05
  enable_ransac: true
  ransac_method: CV2_USAC_MAGSAC
  ransac_reproj_threshold: 8
  ransac_confidence: 0.9999
  ransac_max_iter: 10000
  ransac_num_samples: 4
  match_threshold: 0.2
  setting_geometry: Homography

matcher_zoo:
  # vismatch models
  superpoint+lightglue:
    matcher: superpoint-lightglue
    info:
      name: LightGlue
      source: "ICCV 2023"
      github: https://github.com/cvg/LightGlue
      paper: https://arxiv.org/pdf/2306.13643
      project: null
      display: true
      efficiency: high

  disk+lightglue:
    matcher: disk-lightglue
    info:
      name: LightGlue (DISK)
      source: "ICCV 2023"
      github: https://github.com/cvg/LightGlue
      paper: https://arxiv.org/pdf/2306.13643
      project: null
      display: true
      efficiency: high

  aliked+lightglue:
    matcher: aliked-lightglue
    info:
      name: ALIKED
      source: "ICCV 2023"
      github: https://github.com/Shiaoming/ALIKED
      paper: https://arxiv.org/pdf/2304.03608.pdf
      project: null
      display: true
      efficiency: high

  sift+lightglue:
    matcher: sift-lightglue
    info:
      name: LightGlue (SIFT)
      source: "ICCV 2023"
      github: https://github.com/cvg/LightGlue
      paper: https://arxiv.org/pdf/2306.13643
      project: null
      display: true
      efficiency: high

  loftr:
    matcher: loftr
    info:
      name: LoFTR
      source: "CVPR 2021"
      github: https://github.com/zju3dv/LoFTR
      paper: https://arxiv.org/pdf/2104.00680
      project: https://zju3dv.github.io/loftr
      display: true
      efficiency: medium

  roma:
    matcher: roma
    info:
      name: RoMa
      source: "CVPR 2024"
      github: https://github.com/Parskatt/RoMa
      paper: https://arxiv.org/abs/2305.15404
      project: https://parskatt.github.io/RoMa
      display: true
      efficiency: medium

retrieval_zoo: {}
